from random import Random

from inline_snapshot import external

from gulk_lib.build_deck import build_deck
from gulk_lib.events import NewGame
from gulk_lib.game_config import GameConfig
from gulk_lib.game_state import GameState
from gulk_lib.shuffle_deck import shuffle_deck
from tests.factories import make_bid, make_deal, make_play_card, make_player
from tests.integration.history import apply_events, format_history


def test_new_game():
    player_1, player_2 = make_player(1), make_player(2)

    events = [NewGame(GameConfig([player_1, player_2], jokers=0))]

    state = GameState()
    history = apply_events(state, events)

    assert format_history(history) == external("uuid:new_game.txt")


def test_random_game():
    rng = Random(835975093)  # noqa: S311
    events = [
        NewGame(
            GameConfig(
                [make_player(1), make_player(2), make_player(3), make_player(4)],
                jokers=0,
            )
        ),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=1,
            cards_per_player=1,
            deal_trump=True,
        ),
        make_bid(player_id=2, num_tricks=1),
        make_bid(player_id=3, num_tricks=1),
        make_bid(player_id=4, num_tricks=0),
        make_bid(player_id=1, num_tricks=1),
        make_play_card(player_id=2, card_id=34),
        make_play_card(player_id=3, card_id=40),
        make_play_card(player_id=4, card_id=31),
        make_play_card(player_id=1, card_id=11),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=2,
            cards_per_player=2,
            deal_trump=True,
        ),
        make_bid(player_id=3, num_tricks=1),
        make_bid(player_id=4, num_tricks=0),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=1),
        make_play_card(player_id=3, card_id=30),
        make_play_card(player_id=4, card_id=45),
        make_play_card(player_id=1, card_id=34),
        make_play_card(player_id=2, card_id=40),
        make_play_card(player_id=1, card_id=1),
        make_play_card(player_id=2, card_id=23),
        make_play_card(player_id=3, card_id=48),
        make_play_card(player_id=4, card_id=41),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=3,
            cards_per_player=3,
            deal_trump=True,
        ),
        make_bid(player_id=4, num_tricks=1),
        make_bid(player_id=1, num_tricks=2),
        make_bid(player_id=2, num_tricks=2),
        make_bid(player_id=3, num_tricks=1),
        make_play_card(player_id=4, card_id=35),
        make_play_card(player_id=1, card_id=28),
        make_play_card(player_id=2, card_id=16),
        make_play_card(player_id=3, card_id=37),
        make_play_card(player_id=3, card_id=25),
        make_play_card(player_id=4, card_id=11),
        make_play_card(player_id=1, card_id=9),
        make_play_card(player_id=2, card_id=15),
        make_play_card(player_id=4, card_id=12),
        make_play_card(player_id=1, card_id=51),
        make_play_card(player_id=2, card_id=2),
        make_play_card(player_id=3, card_id=31),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=4,
            cards_per_player=4,
            deal_trump=True,
        ),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=2),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=0),
        make_play_card(player_id=1, card_id=3),
        make_play_card(player_id=2, card_id=36),
        make_play_card(player_id=3, card_id=12),
        make_play_card(player_id=4, card_id=22),
        make_play_card(player_id=4, card_id=50),
        make_play_card(player_id=1, card_id=35),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=3, card_id=39),
        make_play_card(player_id=4, card_id=13),
        make_play_card(player_id=1, card_id=25),
        make_play_card(player_id=2, card_id=20),
        make_play_card(player_id=3, card_id=19),
        make_play_card(player_id=1, card_id=34),
        make_play_card(player_id=2, card_id=28),
        make_play_card(player_id=3, card_id=33),
        make_play_card(player_id=4, card_id=49),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=1,
            cards_per_player=5,
            deal_trump=True,
        ),
        make_bid(player_id=2, num_tricks=1),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=3),
        make_bid(player_id=1, num_tricks=2),
        make_play_card(player_id=2, card_id=51),
        make_play_card(player_id=3, card_id=49),
        make_play_card(player_id=4, card_id=39),
        make_play_card(player_id=1, card_id=46),
        make_play_card(player_id=2, card_id=20),
        make_play_card(player_id=3, card_id=13),
        make_play_card(player_id=4, card_id=19),
        make_play_card(player_id=1, card_id=16),
        make_play_card(player_id=2, card_id=6),
        make_play_card(player_id=3, card_id=10),
        make_play_card(player_id=4, card_id=0),
        make_play_card(player_id=1, card_id=31),
        make_play_card(player_id=3, card_id=43),
        make_play_card(player_id=4, card_id=8),
        make_play_card(player_id=1, card_id=27),
        make_play_card(player_id=2, card_id=42),
        make_play_card(player_id=3, card_id=48),
        make_play_card(player_id=4, card_id=17),
        make_play_card(player_id=1, card_id=30),
        make_play_card(player_id=2, card_id=36),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=2,
            cards_per_player=6,
            deal_trump=True,
        ),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=2),
        make_bid(player_id=1, num_tricks=4),
        make_bid(player_id=2, num_tricks=3),
        make_play_card(player_id=3, card_id=26),
        make_play_card(player_id=4, card_id=30),
        make_play_card(player_id=1, card_id=36),
        make_play_card(player_id=2, card_id=27),
        make_play_card(player_id=1, card_id=45),
        make_play_card(player_id=2, card_id=7),
        make_play_card(player_id=3, card_id=43),
        make_play_card(player_id=4, card_id=14),
        make_play_card(player_id=2, card_id=34),
        make_play_card(player_id=3, card_id=28),
        make_play_card(player_id=4, card_id=6),
        make_play_card(player_id=1, card_id=40),
        make_play_card(player_id=4, card_id=3),
        make_play_card(player_id=1, card_id=25),
        make_play_card(player_id=2, card_id=0),
        make_play_card(player_id=3, card_id=2),
        make_play_card(player_id=4, card_id=18),
        make_play_card(player_id=1, card_id=21),
        make_play_card(player_id=2, card_id=22),
        make_play_card(player_id=3, card_id=10),
        make_play_card(player_id=3, card_id=42),
        make_play_card(player_id=4, card_id=19),
        make_play_card(player_id=1, card_id=13),
        make_play_card(player_id=2, card_id=24),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=3,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=4, num_tricks=5),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=5),
        make_bid(player_id=3, num_tricks=1),
        make_play_card(player_id=4, card_id=2),
        make_play_card(player_id=1, card_id=8),
        make_play_card(player_id=2, card_id=0),
        make_play_card(player_id=3, card_id=6),
        make_play_card(player_id=1, card_id=22),
        make_play_card(player_id=2, card_id=14),
        make_play_card(player_id=3, card_id=25),
        make_play_card(player_id=4, card_id=24),
        make_play_card(player_id=3, card_id=33),
        make_play_card(player_id=4, card_id=36),
        make_play_card(player_id=1, card_id=34),
        make_play_card(player_id=2, card_id=37),
        make_play_card(player_id=2, card_id=50),
        make_play_card(player_id=3, card_id=51),
        make_play_card(player_id=4, card_id=49),
        make_play_card(player_id=1, card_id=13),
        make_play_card(player_id=3, card_id=43),
        make_play_card(player_id=4, card_id=47),
        make_play_card(player_id=1, card_id=10),
        make_play_card(player_id=2, card_id=42),
        make_play_card(player_id=1, card_id=15),
        make_play_card(player_id=2, card_id=26),
        make_play_card(player_id=3, card_id=32),
        make_play_card(player_id=4, card_id=44),
        make_play_card(player_id=1, card_id=17),
        make_play_card(player_id=2, card_id=27),
        make_play_card(player_id=3, card_id=38),
        make_play_card(player_id=4, card_id=40),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=4,
            cards_per_player=7,
            deal_trump=False,
        ),
        make_bid(player_id=1, num_tricks=3),
        make_bid(player_id=2, num_tricks=4),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=5),
        make_play_card(player_id=1, card_id=13),
        make_play_card(player_id=2, card_id=21),
        make_play_card(player_id=3, card_id=20),
        make_play_card(player_id=4, card_id=16),
        make_play_card(player_id=2, card_id=41),
        make_play_card(player_id=3, card_id=36),
        make_play_card(player_id=4, card_id=38),
        make_play_card(player_id=1, card_id=51),
        make_play_card(player_id=1, card_id=5),
        make_play_card(player_id=2, card_id=2),
        make_play_card(player_id=3, card_id=3),
        make_play_card(player_id=4, card_id=6),
        make_play_card(player_id=4, card_id=25),
        make_play_card(player_id=1, card_id=23),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=3, card_id=11),
        make_play_card(player_id=4, card_id=29),
        make_play_card(player_id=1, card_id=31),
        make_play_card(player_id=2, card_id=46),
        make_play_card(player_id=3, card_id=30),
        make_play_card(player_id=1, card_id=22),
        make_play_card(player_id=2, card_id=40),
        make_play_card(player_id=3, card_id=1),
        make_play_card(player_id=4, card_id=33),
        make_play_card(player_id=1, card_id=17),
        make_play_card(player_id=2, card_id=44),
        make_play_card(player_id=3, card_id=26),
        make_play_card(player_id=4, card_id=32),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=1,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=2, num_tricks=6),
        make_bid(player_id=3, num_tricks=5),
        make_bid(player_id=4, num_tricks=5),
        make_bid(player_id=1, num_tricks=2),
        make_play_card(player_id=2, card_id=46),
        make_play_card(player_id=3, card_id=49),
        make_play_card(player_id=4, card_id=47),
        make_play_card(player_id=1, card_id=50),
        make_play_card(player_id=1, card_id=22),
        make_play_card(player_id=2, card_id=33),
        make_play_card(player_id=3, card_id=18),
        make_play_card(player_id=4, card_id=20),
        make_play_card(player_id=1, card_id=24),
        make_play_card(player_id=2, card_id=2),
        make_play_card(player_id=3, card_id=7),
        make_play_card(player_id=4, card_id=23),
        make_play_card(player_id=1, card_id=32),
        make_play_card(player_id=2, card_id=43),
        make_play_card(player_id=3, card_id=29),
        make_play_card(player_id=4, card_id=34),
        make_play_card(player_id=4, card_id=0),
        make_play_card(player_id=1, card_id=38),
        make_play_card(player_id=2, card_id=10),
        make_play_card(player_id=3, card_id=3),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=3, card_id=9),
        make_play_card(player_id=4, card_id=25),
        make_play_card(player_id=1, card_id=42),
        make_play_card(player_id=4, card_id=19),
        make_play_card(player_id=1, card_id=21),
        make_play_card(player_id=2, card_id=12),
        make_play_card(player_id=3, card_id=37),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=2,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=3, num_tricks=3),
        make_bid(player_id=4, num_tricks=3),
        make_bid(player_id=1, num_tricks=3),
        make_bid(player_id=2, num_tricks=3),
        make_play_card(player_id=3, card_id=28),
        make_play_card(player_id=4, card_id=38),
        make_play_card(player_id=1, card_id=41),
        make_play_card(player_id=2, card_id=35),
        make_play_card(player_id=1, card_id=0),
        make_play_card(player_id=2, card_id=11),
        make_play_card(player_id=3, card_id=26),
        make_play_card(player_id=4, card_id=2),
        make_play_card(player_id=2, card_id=36),
        make_play_card(player_id=3, card_id=27),
        make_play_card(player_id=4, card_id=29),
        make_play_card(player_id=1, card_id=21),
        make_play_card(player_id=2, card_id=17),
        make_play_card(player_id=3, card_id=14),
        make_play_card(player_id=4, card_id=22),
        make_play_card(player_id=1, card_id=16),
        make_play_card(player_id=4, card_id=42),
        make_play_card(player_id=1, card_id=19),
        make_play_card(player_id=2, card_id=46),
        make_play_card(player_id=3, card_id=39),
        make_play_card(player_id=2, card_id=20),
        make_play_card(player_id=3, card_id=50),
        make_play_card(player_id=4, card_id=47),
        make_play_card(player_id=1, card_id=1),
        make_play_card(player_id=3, card_id=33),
        make_play_card(player_id=4, card_id=4),
        make_play_card(player_id=1, card_id=9),
        make_play_card(player_id=2, card_id=7),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=3,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=4, num_tricks=5),
        make_bid(player_id=1, num_tricks=4),
        make_bid(player_id=2, num_tricks=2),
        make_bid(player_id=3, num_tricks=6),
        make_play_card(player_id=4, card_id=43),
        make_play_card(player_id=1, card_id=46),
        make_play_card(player_id=2, card_id=41),
        make_play_card(player_id=3, card_id=11),
        make_play_card(player_id=1, card_id=25),
        make_play_card(player_id=2, card_id=16),
        make_play_card(player_id=3, card_id=6),
        make_play_card(player_id=4, card_id=29),
        make_play_card(player_id=1, card_id=4),
        make_play_card(player_id=2, card_id=5),
        make_play_card(player_id=3, card_id=8),
        make_play_card(player_id=4, card_id=12),
        make_play_card(player_id=4, card_id=32),
        make_play_card(player_id=1, card_id=27),
        make_play_card(player_id=2, card_id=44),
        make_play_card(player_id=3, card_id=34),
        make_play_card(player_id=3, card_id=36),
        make_play_card(player_id=4, card_id=35),
        make_play_card(player_id=1, card_id=1),
        make_play_card(player_id=2, card_id=50),
        make_play_card(player_id=3, card_id=7),
        make_play_card(player_id=4, card_id=51),
        make_play_card(player_id=1, card_id=17),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=1, card_id=49),
        make_play_card(player_id=2, card_id=40),
        make_play_card(player_id=3, card_id=3),
        make_play_card(player_id=4, card_id=37),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=4,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=1, num_tricks=4),
        make_bid(player_id=2, num_tricks=3),
        make_bid(player_id=3, num_tricks=4),
        make_bid(player_id=4, num_tricks=5),
        make_play_card(player_id=1, card_id=17),
        make_play_card(player_id=2, card_id=18),
        make_play_card(player_id=3, card_id=25),
        make_play_card(player_id=4, card_id=16),
        make_play_card(player_id=3, card_id=50),
        make_play_card(player_id=4, card_id=41),
        make_play_card(player_id=1, card_id=48),
        make_play_card(player_id=2, card_id=46),
        make_play_card(player_id=3, card_id=5),
        make_play_card(player_id=4, card_id=6),
        make_play_card(player_id=1, card_id=11),
        make_play_card(player_id=2, card_id=1),
        make_play_card(player_id=1, card_id=15),
        make_play_card(player_id=2, card_id=19),
        make_play_card(player_id=3, card_id=40),
        make_play_card(player_id=4, card_id=21),
        make_play_card(player_id=4, card_id=27),
        make_play_card(player_id=1, card_id=30),
        make_play_card(player_id=2, card_id=31),
        make_play_card(player_id=3, card_id=34),
        make_play_card(player_id=3, card_id=37),
        make_play_card(player_id=4, card_id=32),
        make_play_card(player_id=1, card_id=38),
        make_play_card(player_id=2, card_id=4),
        make_play_card(player_id=2, card_id=22),
        make_play_card(player_id=3, card_id=36),
        make_play_card(player_id=4, card_id=29),
        make_play_card(player_id=1, card_id=14),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=1,
            cards_per_player=7,
            deal_trump=False,
        ),
        make_bid(player_id=2, num_tricks=1),
        make_bid(player_id=3, num_tricks=6),
        make_bid(player_id=4, num_tricks=4),
        make_bid(player_id=1, num_tricks=3),
        make_play_card(player_id=2, card_id=23),
        make_play_card(player_id=3, card_id=14),
        make_play_card(player_id=4, card_id=38),
        make_play_card(player_id=1, card_id=15),
        make_play_card(player_id=2, card_id=33),
        make_play_card(player_id=3, card_id=36),
        make_play_card(player_id=4, card_id=35),
        make_play_card(player_id=1, card_id=37),
        make_play_card(player_id=1, card_id=41),
        make_play_card(player_id=2, card_id=50),
        make_play_card(player_id=3, card_id=45),
        make_play_card(player_id=4, card_id=44),
        make_play_card(player_id=2, card_id=20),
        make_play_card(player_id=3, card_id=22),
        make_play_card(player_id=4, card_id=5),
        make_play_card(player_id=1, card_id=7),
        make_play_card(player_id=3, card_id=6),
        make_play_card(player_id=4, card_id=9),
        make_play_card(player_id=1, card_id=12),
        make_play_card(player_id=2, card_id=29),
        make_play_card(player_id=1, card_id=49),
        make_play_card(player_id=2, card_id=39),
        make_play_card(player_id=3, card_id=43),
        make_play_card(player_id=4, card_id=11),
        make_play_card(player_id=1, card_id=1),
        make_play_card(player_id=2, card_id=31),
        make_play_card(player_id=3, card_id=26),
        make_play_card(player_id=4, card_id=3),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=2,
            cards_per_player=7,
            deal_trump=True,
        ),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=3),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=2),
        make_play_card(player_id=3, card_id=39),
        make_play_card(player_id=4, card_id=43),
        make_play_card(player_id=1, card_id=46),
        make_play_card(player_id=2, card_id=47),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=3, card_id=9),
        make_play_card(player_id=4, card_id=49),
        make_play_card(player_id=1, card_id=45),
        make_play_card(player_id=3, card_id=3),
        make_play_card(player_id=4, card_id=6),
        make_play_card(player_id=1, card_id=0),
        make_play_card(player_id=2, card_id=8),
        make_play_card(player_id=2, card_id=41),
        make_play_card(player_id=3, card_id=25),
        make_play_card(player_id=4, card_id=27),
        make_play_card(player_id=1, card_id=38),
        make_play_card(player_id=2, card_id=28),
        make_play_card(player_id=3, card_id=29),
        make_play_card(player_id=4, card_id=30),
        make_play_card(player_id=1, card_id=26),
        make_play_card(player_id=4, card_id=16),
        make_play_card(player_id=1, card_id=15),
        make_play_card(player_id=2, card_id=5),
        make_play_card(player_id=3, card_id=23),
        make_play_card(player_id=2, card_id=51),
        make_play_card(player_id=3, card_id=4),
        make_play_card(player_id=4, card_id=32),
        make_play_card(player_id=1, card_id=11),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=3,
            cards_per_player=6,
            deal_trump=True,
        ),
        make_bid(player_id=4, num_tricks=0),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=3),
        make_bid(player_id=3, num_tricks=3),
        make_play_card(player_id=4, card_id=18),
        make_play_card(player_id=1, card_id=20),
        make_play_card(player_id=2, card_id=34),
        make_play_card(player_id=3, card_id=22),
        make_play_card(player_id=3, card_id=2),
        make_play_card(player_id=4, card_id=1),
        make_play_card(player_id=1, card_id=5),
        make_play_card(player_id=2, card_id=8),
        make_play_card(player_id=2, card_id=47),
        make_play_card(player_id=3, card_id=44),
        make_play_card(player_id=4, card_id=12),
        make_play_card(player_id=1, card_id=48),
        make_play_card(player_id=1, card_id=35),
        make_play_card(player_id=2, card_id=28),
        make_play_card(player_id=3, card_id=31),
        make_play_card(player_id=4, card_id=37),
        make_play_card(player_id=4, card_id=7),
        make_play_card(player_id=1, card_id=3),
        make_play_card(player_id=2, card_id=50),
        make_play_card(player_id=3, card_id=6),
        make_play_card(player_id=2, card_id=45),
        make_play_card(player_id=3, card_id=49),
        make_play_card(player_id=4, card_id=23),
        make_play_card(player_id=1, card_id=46),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=4,
            cards_per_player=5,
            deal_trump=True,
        ),
        make_bid(player_id=1, num_tricks=4),
        make_bid(player_id=2, num_tricks=3),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=1),
        make_play_card(player_id=1, card_id=19),
        make_play_card(player_id=2, card_id=24),
        make_play_card(player_id=3, card_id=22),
        make_play_card(player_id=4, card_id=18),
        make_play_card(player_id=2, card_id=11),
        make_play_card(player_id=3, card_id=37),
        make_play_card(player_id=4, card_id=2),
        make_play_card(player_id=1, card_id=25),
        make_play_card(player_id=2, card_id=13),
        make_play_card(player_id=3, card_id=47),
        make_play_card(player_id=4, card_id=38),
        make_play_card(player_id=1, card_id=16),
        make_play_card(player_id=3, card_id=40),
        make_play_card(player_id=4, card_id=41),
        make_play_card(player_id=1, card_id=49),
        make_play_card(player_id=2, card_id=26),
        make_play_card(player_id=1, card_id=45),
        make_play_card(player_id=2, card_id=3),
        make_play_card(player_id=3, card_id=51),
        make_play_card(player_id=4, card_id=27),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=1,
            cards_per_player=4,
            deal_trump=True,
        ),
        make_bid(player_id=2, num_tricks=3),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=3),
        make_bid(player_id=1, num_tricks=2),
        make_play_card(player_id=2, card_id=35),
        make_play_card(player_id=3, card_id=23),
        make_play_card(player_id=4, card_id=18),
        make_play_card(player_id=1, card_id=15),
        make_play_card(player_id=2, card_id=31),
        make_play_card(player_id=3, card_id=51),
        make_play_card(player_id=4, card_id=6),
        make_play_card(player_id=1, card_id=1),
        make_play_card(player_id=3, card_id=2),
        make_play_card(player_id=4, card_id=5),
        make_play_card(player_id=1, card_id=4),
        make_play_card(player_id=2, card_id=45),
        make_play_card(player_id=2, card_id=48),
        make_play_card(player_id=3, card_id=16),
        make_play_card(player_id=4, card_id=39),
        make_play_card(player_id=1, card_id=20),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=2,
            cards_per_player=3,
            deal_trump=True,
        ),
        make_bid(player_id=3, num_tricks=2),
        make_bid(player_id=4, num_tricks=2),
        make_bid(player_id=1, num_tricks=2),
        make_bid(player_id=2, num_tricks=1),
        make_play_card(player_id=3, card_id=34),
        make_play_card(player_id=4, card_id=22),
        make_play_card(player_id=1, card_id=42),
        make_play_card(player_id=2, card_id=50),
        make_play_card(player_id=2, card_id=23),
        make_play_card(player_id=3, card_id=8),
        make_play_card(player_id=4, card_id=3),
        make_play_card(player_id=1, card_id=16),
        make_play_card(player_id=2, card_id=45),
        make_play_card(player_id=3, card_id=10),
        make_play_card(player_id=4, card_id=39),
        make_play_card(player_id=1, card_id=0),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=3,
            cards_per_player=2,
            deal_trump=True,
        ),
        make_bid(player_id=4, num_tricks=1),
        make_bid(player_id=1, num_tricks=1),
        make_bid(player_id=2, num_tricks=1),
        make_bid(player_id=3, num_tricks=0),
        make_play_card(player_id=4, card_id=31),
        make_play_card(player_id=1, card_id=34),
        make_play_card(player_id=2, card_id=28),
        make_play_card(player_id=3, card_id=44),
        make_play_card(player_id=1, card_id=17),
        make_play_card(player_id=2, card_id=43),
        make_play_card(player_id=3, card_id=47),
        make_play_card(player_id=4, card_id=38),
        make_deal(
            shuffle_deck(build_deck(0), rng),
            dealer_id=4,
            cards_per_player=1,
            deal_trump=True,
        ),
        make_bid(player_id=1, num_tricks=0),
        make_bid(player_id=2, num_tricks=0),
        make_bid(player_id=3, num_tricks=1),
        make_bid(player_id=4, num_tricks=1),
        make_play_card(player_id=1, card_id=13),
        make_play_card(player_id=2, card_id=29),
        make_play_card(player_id=3, card_id=35),
        make_play_card(player_id=4, card_id=27),
    ]

    state = GameState()
    history = apply_events(state, events)

    assert format_history(history) == external("uuid:random_game.txt")
